import streamlit as st
import pandas as pd
import datetime
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
import requests
from bs4 import BeautifulSoup

# Dugin Agenda Items
AGENDA_ITEMS = {
    "Dismantling NATO Alliances": ["NATO", "withdraw troops", "Trump NATO", "defund NATO"],
    "Weakening U.S. Intelligence Community": ["FBI purge", "CIA cuts", "intelligence overhaul"],
    "Pulling Troops from Strategic Regions": ["troop withdrawal", "military exit", "Trump Middle East pullout"],
    "Promoting Christian Nationalism": ["Christian nationalism", "evangelical politics", "dominionism"],
    "Delegitimizing Elections": ["voter fraud", "rigged election", "fake ballots"],
    "Reducing Federal Power Over States": ["states' rights", "federal overreach", "sovereignty acts"],
    "Isolationist Foreign Policy": ["America First", "foreign aid cuts", "Trump isolationism"],
    "Discrediting Free Press": ["fake news", "enemy of the people", "media lies"],
    "Fostering Civil Unrest": ["civil war", "armed protest", "Trump militia"],
    "Undermining Global Democratic Norms": ["autocracy rise", "authoritarian alliance", "dismantle democracy"]
}

@st.cache_data(show_spinner=False)
def fetch_progress_and_headlines():
    headers = {"User-Agent": "Mozilla/5.0"}
    base_url = "https://news.google.com/search?q={query}&hl=en-US&gl=US&ceid=US:en"
    result = {}

    for item, keywords in AGENDA_ITEMS.items():
        total_hits = 0
        seen_titles = set()
        headlines = []

        for keyword in keywords[:2]:
            try:
                url = base_url.format(query=keyword.replace(" ", "+"))
                response = requests.get(url, headers=headers, timeout=5)
                soup = BeautifulSoup(response.content, "html.parser")
                for tag in soup.select("article h3 a"):
                    title = tag.text.strip()
                    href = tag.get("href", "")
                    if href.startswith("./"):
                        href = "https://news.google.com" + href[1:]
                    if title and title not in seen_titles:
                        seen_titles.add(title)
                        headlines.append((title, href))
                        total_hits += 1
            except Exception as e:
                print(f"Error for keyword '{keyword}': {e}")
                continue

        if total_hits <= 3:
            score = 10
        elif total_hits <= 7:
            score = 30
        elif total_hits <= 15:
            score = 60
        elif total_hits <= 25:
            score = 80
        else:
            score = 100

        result[item] = {
            "progress": score,
            "headlines": headlines[:3],
            "hit_count": total_hits
        }

    return result

# Sidebar
st.sidebar.title("Dugin Context")
st.sidebar.markdown("""
Aleksandr Dugin, a Russian political philosopher, promotes a Eurasian worldview opposed to liberal Western democracy.

This dashboard tracks the advancement of his ideological blueprint through U.S. politics.
""")

# Main Title
st.title("Dugin-Trump Agenda Tracker")
st.markdown("Live monitoring of 10 strategic objectives aligned with Dugin's ideology to evaluate their adoption within U.S. governance.")

# Data Fetch
data = fetch_progress_and_headlines()
st.markdown("### Current Progress Snapshot (Auto-Sourced)")

for item, details in data.items():
    st.progress(details["progress"], text=f"{item}: {details['progress']}%")
    st.caption(f"📰 {details['hit_count']} articles matched")
    with st.expander("See headlines"):
        for title, url in details["headlines"]:
            st.markdown(f"- [{title}]({url})")

# Export Placeholder
if st.button("Export Intelligence PDF"):
    st.info("PDF export coming soon.")

# Email Report
def send_weekly_email():
    sender_email = os.getenv("EMAIL_USER")
    receiver_email = "scarfaceforward@gmail.com"
    password = os.getenv("EMAIL_PASS")

    message = MIMEMultipart("alternative")
    message["Subject"] = "Weekly Dugin-Trump Agenda Progress Update"
    message["From"] = sender_email
    message["To"] = receiver_email

    html = f"<html><body><h2>Dugin-Trump Agenda Weekly Report - {datetime.date.today()}</h2><ul>"
    for item, details in data.items():
        html += f"<li><strong>{item}:</strong> {details['progress']}%</li>"
    html += "</ul><p>This report was auto-generated by the Dugin-Trump Tracker System.</p></body></html>"

    part = MIMEText(html, "html")
    message.attach(part)

    with smtplib.SMTP_SSL("smtp.mail.yahoo.com", 465) as server:
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, message.as_string())

if st.button("Send Weekly Email Report"):
    send_weekly_email()
    st.success("Email sent to scarfaceforward@gmail.com")
